Namespace Components
    Public Class Keyboard
        Private Property Buffer As Byte()
        Private Property Mapping As Dictionary(Of Char, UInt16)
        Sub New()
            Me.Buffer = New Byte(15) {}
            Me.Mapping = New Dictionary(Of Char, UInt16)
            Me.Mapping.Add(Char.Parse("A"), 4)
            Me.Mapping.Add(Char.Parse("B"), 10)
            Me.Mapping.Add(Char.Parse("C"), 16)
            Me.Mapping.Add(Char.Parse("D"), 22)
            Me.Mapping.Add(Char.Parse("E"), 28)
            Me.Mapping.Add(Char.Parse("F"), 34)
            Me.Mapping.Add(Char.Parse("G"), 40)
            Me.Mapping.Add(Char.Parse("H"), 46)
            Me.Mapping.Add(Char.Parse("I"), 52)
            Me.Mapping.Add(Char.Parse("J"), 58)
            Me.Mapping.Add(Char.Parse("K"), 64)
            Me.Mapping.Add(Char.Parse("L"), 70)
            Me.Mapping.Add(Char.Parse("M"), 76)
            Me.Mapping.Add(Char.Parse("N"), 82)
            Me.Mapping.Add(Char.Parse("O"), 88)
            Me.Mapping.Add(Char.Parse("P"), 94)
            Me.Mapping.Add(Char.Parse("Q"), 100)
            Me.Mapping.Add(Char.Parse("R"), 106)
            Me.Mapping.Add(Char.Parse("S"), 112)
            Me.Mapping.Add(Char.Parse("T"), 118)
            Me.Mapping.Add(Char.Parse("U"), 124)
            Me.Mapping.Add(Char.Parse("V"), 130)
            Me.Mapping.Add(Char.Parse("W"), 136)
            Me.Mapping.Add(Char.Parse("X"), 142)
            Me.Mapping.Add(Char.Parse("Y"), 148)
            Me.Mapping.Add(Char.Parse("Z"), 154)
            Me.Mapping.Add(Char.Parse("1"), 160)
            Me.Mapping.Add(Char.Parse("2"), 166)
            Me.Mapping.Add(Char.Parse("3"), 172)
            Me.Mapping.Add(Char.Parse("4"), 178)
            Me.Mapping.Add(Char.Parse("5"), 184)
            Me.Mapping.Add(Char.Parse("6"), 190)
            Me.Mapping.Add(Char.Parse("7"), 196)
            Me.Mapping.Add(Char.Parse("8"), 202)
            Me.Mapping.Add(Char.Parse("9"), 208)
            Me.Mapping.Add(Char.Parse("0"), 214)
            Me.Mapping.Add(Char.Parse("!"), 220)
            Me.Mapping.Add(Char.Parse("?"), 226)
            Me.Mapping.Add(Char.Parse("+"), 232)
            Me.Mapping.Add(Char.Parse("-"), 238)
            Me.Mapping.Add(Char.Parse("*"), 244)
            Me.Mapping.Add(Char.Parse("/"), 250)
            Me.Mapping.Add(Char.Parse("."), 256)
            Me.Mapping.Add(Char.Parse(":"), 262)
            Me.Mapping.Add(Char.Parse("→"), 268)
            Me.Mapping.Add(Char.Parse("←"), 274)
            Me.Mapping.Add(Char.Parse("↑"), 280)
            Me.Mapping.Add(Char.Parse("↓"), 286)
            Me.Mapping.Add(Char.Parse("="), 292)
            Me.Mapping.Add(Char.Parse(">"), 298)
            Me.Mapping.Add(Char.Parse("<"), 304)
            Me.Mapping.Add(Char.Parse("'"), 310)
            Me.Mapping.Add(Char.Parse("["), 316)
            Me.Mapping.Add(Char.Parse("|"), 322)
            Me.Mapping.Add(Char.Parse("]"), 328)
            Me.Mapping.Add(Char.Parse("\"), 334)
            Me.Mapping.Add(Char.Parse(" "), 340)
            Me.Mapping.Add(Char.Parse(","), 346)
        End Sub
    End Class
End Namespace