'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pixel.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property characters() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("characters", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property fonts() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fonts", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ;*************************************************************
        '''; NAME			: PRINT
        '''; DESCRIPTION	: PRINTS STRING ON COORDINATES
        '''; PARAMS		: X Y [ADDRESS]
        ''';*************************************************************
        ''':@print
        '''	store [@print_addr]
        '''	store [@print_y]
        '''	store [@print_x]
        '''	strlen_addr [@print_addr][@print_len]
        ''':@print_loop
        '''	call [@print_next_char]
        '''	ifv [@print_i][@print_len] jmp [@print_cleanup]
        '''	jmp [@print_loop]
        ''':@print_next_char
        '''	print_addr [@print_x][@print_y][@print_i][@print_addr]
        '''	inc [@print_i [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Print() As String
            Get
                Return ResourceManager.GetString("Print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ;*************************************************************
        '''; NAME			: PRINTV
        '''; DESCRIPTION	: PRINTS VARIABLE NUMBER ON COORDINATES
        '''; PARAMS		: X Y [ADDRESS]
        ''';*************************************************************
        ''':@printv
        '''	store [@printv_var]
        '''	store [@printv_y]
        '''	store [@printv_x]
        '''	print_addrv [@printv_x][@printv_y][@printv_var]
        '''	return
        ''':@printv_var	0
        ''':@printv_x		0
        ''':@printv_y		0.
        '''</summary>
        Friend ReadOnly Property Print_num() As String
            Get
                Return ResourceManager.GetString("Print_num", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ;*************************************************************
        '''; NAME			: SCROLL
        '''; DESCRIPTION	: SHIFT DISPLAY BUFFER
        '''; PARAMS		: DIRECTION STEPS
        ''';*************************************************************
        '''
        ''':@scroll
        '''	store [@scroll_steps]
        '''	store [@scroll_direction]
        '''	scr [@scroll_direction][@scroll_steps]
        '''	store [@scroll_steps] #0
        '''	store [@scroll_direction] #0
        '''	return
        ''':@scroll_steps		0
        ''':@scroll_direction	0
        '''	.
        '''</summary>
        Friend ReadOnly Property Scroll() As String
            Get
                Return ResourceManager.GetString("Scroll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ;*************************************************************
        '''; NAME			: SLEEP
        '''; DESCRIPTION	: MAKE VM SLEEP FOR N CYCLES
        '''; PARAMS		: N
        ''';*************************************************************
        '''
        ''':@sleep
        '''	store [@sleep_timer]
        ''':@sleep_loop
        '''	if [@sleep_timer] #0 return
        '''	dec [@sleep_timer] #1
        '''	jmp [@sleep_loop]
        ''':@sleep_timer	0
        '''	.
        '''</summary>
        Friend ReadOnly Property Sleep() As String
            Get
                Return ResourceManager.GetString("Sleep", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
